---
title: "Lab 3"
subtitle: "Part 4"
output: html_notebook
---


```{r}
# load libraries
library(tidyverse)
library(cluster)
library(NbClust)
library(rpart.plot)
library(RColorBrewer)
library(rpart)
library(rattle)
```


## Online News Dataset

```{r}
newsShort <- read_csv("OnlineNews.csv")%>%
  select("n_tokens_title", "n_tokens_content", "n_unique_tokens", "n_non_stop_words", "num_hrefs", "num_imgs", "num_videos", "average_token_length", "num_keywords", "kw_max_max", "global_sentiment_polarity", "avg_positive_polarity", "title_subjectivity", "title_sentiment_polarity", "abs_title_subjectivity", "abs_title_sentiment_polarity", "shares")
head(newsShort)
```



```{r}
data <- data.frame(newsShort)
```


```{r}
top.n.custs <- function (data, cols, n = 5) {
  #Initialize a vector to hold customers being removed
  idx.to.remove <- integer(0)
  for (c in cols) {
    # For every column in the data we passed to this function
    #Sort column "c" in descending order (bigger on top)
    #Order returns the sorted index (e.g. row 15, 3, 7, 1, ...) rather than the actual values sorted.
    col.order <- order(data[, c], decreasing = T)
    #Take the first n of the sorted column C to
    #combine and de-duplicate the row ids that need to be removed
    idx <- head(col.order, n)
    idx.to.remove <- union(idx.to.remove, idx)
  }
  #Return the indexes of customers to be removed
  return(idx.to.remove)
}
```


```{r}
#How Many Customers to be Removed?
top.custs <-top.n.custs(data, cols = 1:5,n=5)
length(top.custs)
```

```{r}
#Examine the customers
data[top.custs,]
```


```{r}
#Remove the Customers
data.rm.top<-data[-c(top.custs),]
#Examine summary stats for the remaining data
print(summary(data.rm.top))
```

```{r}
#Set the seed for reproducibility
set.seed(76964057)
#Try K from 2 to 20
rng<-2:20
#Number of times to run the K Means algorithm
tries <-100
#Set up an empty vector to hold all of points
avg.totw.ss <-integer(length(rng))
avg.totb.ss <- integer(length(rng))
avg.tot.ss <- integer(length(rng))
```



```{r}
# For each value of the range variable
for (v in rng) {
  #Set up an empty vectors to hold the tries
  v.totw.ss <- integer(tries)
  b.totb.ss <- integer(tries)
  tot.ss <- integer(tries)
  #Run kmeans
  for (i in 1:tries) {
    k.temp <- kmeans(data.rm.top, centers = v,iter.max=30)
    #Store the total withinss
    v.totw.ss[i] <- k.temp$tot.withinss
    #Store the betweenss
    b.totb.ss[i] <- k.temp$betweenss
    #Store the total sum of squares
    tot.ss[i] <- k.temp$totss
  }
  #Average the withinss and betweenss
  avg.totw.ss[v - 1] <- mean(v.totw.ss)
  avg.totb.ss[v - 1] <- mean(b.totb.ss)
  avg.tot.ss[v - 1] <- mean(tot.ss)
}
```


```{r}
plot(rng,avg.totw.ss,type="b", main="Total Within SS by Various K",
ylab="Average Total Within Sum of Squares",
xlab="Value of K")
```


```{r}
plot(rng,avg.totb.ss,type="b", main="Total between SS by Various K",
ylab="Average Total Between Sum of Squares",
xlab="Value of K")
```

```{r}
#Plot the ratio of betweenss/total ss and withinss / total ss for evaluation
plot(rng,avg.totb.ss/avg.tot.ss,type="b", main="Ratio of between ss / the total ss by Various K",
ylab="Ratio Between SS / Total SS",
xlab="Value of K")
abline(h=0.85, col="red")
```


```{r}
plot(rng,avg.totw.ss/avg.tot.ss,type="b", main="Ratio of within ss / the total ss by Various K",
ylab="Ratio Between SS / Total SS",
xlab="Value of K")
abline(h=0.15, col="red")
```


```{r}
#Create the best number of clusters, Remove columns 1 and 2
n <- 13
k <-kmeans(data.rm.top[,-c(1,2)], centers=n)
#Display&nbsp;cluster centers
print(k$centers)
```


```{r}
#Give a count of data points in each cluster
print(table(k$cluster))
```


```{r}
clusplot(data.rm.top, k$cluster, main='2D representation of the Cluster solution',
color=TRUE, shade=TRUE,
labels=2, lines=0)
```

```{r}
#end of document
```

